- name: Install Apache
  hosts: webservers
  become: yes
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
    - name: Overwrite index page
      copy:
        src: ./index.html
        dest: /var/www/html/index.html
    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes
